# Generated by Django 3.2.6 on 2021-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book1',
            name='is_deleted',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
